# Generated by Django 3.1.12 on 2021-07-17 01:14

from django.db import migrations, models
import esite.jaen_cms.models.account


class Migration(migrations.Migration):

    dependencies = [
        ('jaen_cms', '0002_jaenemailformfield_jaenemailformpage_jaenemailformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaenaccount',
            name='encryption_token',
            field=models.CharField(blank=True, default=esite.jaen_cms.models.account.random_token, help_text='Required. Generated sha256 hash.', max_length=256, verbose_name='encryption token'),
        ),
    ]
