name: heimdall

on: [push]

jobs:
  heimdall-ccms-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo npm i -g apollo
      - run: |
          sudo npm i -g apollo-codegen
      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      # If you need to, you can check out your repo to a different location
      - uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.CR_PAT }}
          pal-repo-name: snek-shipyard/heimdall-action
          # the following input gets passed to the private action
          structure-url: 'https://origin.snek.at/graphql'
          data-url: 'https://origin.snek.at/graphql/'
          storage-path: ${{ github.workspace }}/.private-action/storage.crypto
          storage-encryption-key: ${{ secrets.STORAGE_ENCRYPTION_KEY }}
