name: heimdall

on: [push]

jobs:
  heimdall-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo npm install yarn apollo @snek-at/heimdall -g
      # If you need to, you can check out your repo to a different location
      - uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: ${{ secrets.REPO_TOKEN }}
          pal-repo-name: snek-shipyard/heimdall-action
          # the following input gets passed to the private action
          structure-url: 'https://origin.snek.at/graphql/'
          data-url: 'https://origin.snek.at/graphql/'
          storage-path: ${{ github.workspace }}/.private-action/storage.crypto
          storage-encryption-key: ${{ secrets.STORAGE_ENCRYPTION_KEY }}
          drop-hash: ${{ github.sha }}
