name: heimdall

on: [push]

jobs:
  heimdall-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install yarn && yarn add @snek-at/heimdall
      - run: yarn heimdall generate https://dev.kanbon.cloud/graphql/ --drop-version 0.0.${{ github.run_number }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: drop
          path: |
            drop-*.tgz
