name: heimdall

on: [push]

jobs:
  heimdall-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install yarn @snek-at/heimdall graphql -g
      - run: heimdall generate https://dev.kanbon.cloud/graphql/ --drop-version ${{ github.sha }}
